if Theater.count == 0
   Theater.create([
    {official: 'ユナイテッド・シネマ 札幌' , name: 'sapporo'},
    {official: 'シネプレックス 旭川', name: 'asahikawa'},
    {official: 'ユナイテッド・シネマ フォルテ宮城大河原', name: 'ogawara'},
    {official: 'ユナイテッド・シネマ 水戸', name: 'mito'},
    {official: 'シネプレックス つくば', name: 'tsukuba'},
    {official: 'ユナイテッド・シネマ アシコタウンあしかが', name: 'ashikaga'},
    {official: 'ユナイテッド・シネマ 前橋', name: 'maebashi'},
    {official: 'ユナイテッド・シネマ 浦和', name: 'urawa'},
    {official: 'ユナイテッド・シネマ ウニクス南古谷', name: 'minamifuruya'},
    {official: 'ユナイテッド・シネマ 春日部', name: 'kasukabe'},
    {official: 'ユナイテッド・シネマ 入間', name: 'iruma'},
    {official: 'シネプレックス新座', name: 'niza'},
    {official: 'ユナイテッド・シネマ 幸手', name: 'satte'},
    {official: 'ユナイテッド・シネマ わかば', name: 'wakaba'},
    {official: 'ユナイテッド・シネマ ウニクス上里', name: 'kamisato'},
    {official: 'シネプレックス 幕張', name: 'makuhari'},
    {official: 'ユナイテッド・シネマ テラスモール松戸', name:  'matsudo'},
    {official: 'ユナイテッド・シネマ アクアシティお台場',  name:  'odaiba'},
    {official: 'ユナイテッド・シネマ 豊洲',  name:  'toyosu'},
    {official: 'ユナイテッド・シネマ としまえん',  name:  'toshimaen'},
    {official: 'シネプレックス 平塚', name: 'hiratsuka'},
    {official: 'ユナイテッド・シネマ 新潟', name:  'niigata'},
    {official: 'ユナイテッド・シネマ 金沢',  name: 'kanazawa'},
    {official: 'ユナイテッド・シネマ 豊橋18', name: 'toyohashi'},
    {official: 'ユナイテッド・シネマ 岡崎', name: 'okazaki'},
    {official: 'ユナイテッド・シネマ 稲沢', name: 'inazawa'},
    {official: 'ユナイテッド・シネマ 阿久比', name: 'agui'},
    {official: 'ユナイテッド・シネマ 大津', name: 'otsu'},
    {official: 'ユナイテッド・シネマ 岸和田', name: 'kishiwada'},
    {official: 'ユナイテッド・シネマ 枚方', name: 'hirakata'},
    {official: 'ユナイテッド・シネマ 橿原', name: 'kashihara'},
    {official: 'ユナイテッド・シネマ フジグラン今治', name: 'imabari'},
    {official: 'シネプレックス 小倉', name: 'kokura'},
    {official: 'ユナイテッド・シネマ キャナルシティ13', name: 'canalcity'},
    {official: 'ユナイテッド・シネマ 福岡ももち', name: 'fukuokamomochi'},
    {official: 'ユナイテッド・シネマ なかま16', name: 'nakama'},
    {official: 'ユナイテッド・シネマ トリアス久山', name: 'hisayama'},
    {official: 'ユナイテッド・シネマ 長崎', name: 'nagasaki'},
    {official: 'ユナイテッド・シネマ 熊本', name: 'kumamoto'},
    {official: 'ユナイテッド・シネマ PARCOCITY浦添', name: 'urasoe'}
   ])
end